#!/usr/bin/env python3
"""Generate the chip-level LVS deck from the IHP PDK's own sg13g2.lvs.

    python scripts/make_lvs_deck.py <PDK_ROOT>/<PDK> build/sg13g2_chip.lvs

The output is the PDK deck with two changes:

1. its `# %include rule_decks/...` lines point to the PDK by absolute path,
   so the deck can live outside the PDK tree;
2. right after `align`, the foundry I/O library cells (sg13g2_IOPad*,
   sg13g2_Corner, sg13g2_Filler*) are turned into black boxes with
   `blank_circuit`: LVS then checks every connection to their pins but not
   their contents.

Why: at the PDK revision this flow uses, the sg13g2_io CDL netlists do not
match what the same PDK's LVS deck extracts from the sg13g2_io GDS (for
example sg13g2_DCNDiode: one DANTENNA with m=2 in the CDL, two m=1 devices
plus a ptap1 tap in the extraction). Those cells are pre-verified foundry
IP; comparing them as black boxes is the usual chip-level practice. Device
extraction and comparison rules for everything else are the foundry's.
"""

import re
import sys
from pathlib import Path

BLACK_BOXES = ["sg13g2_IOPad*", "sg13g2_Corner", "sg13g2_Filler*"]


def main() -> None:
    pdk, out = Path(sys.argv[1]), Path(sys.argv[2])
    lvs_dir = pdk / "libs.tech" / "klayout" / "tech" / "lvs"
    text = (lvs_dir / "sg13g2.lvs").read_text()

    text, n_inc = re.subn(r"^(#\s*%include\s+)(rule_decks/)", rf"\g<1>{lvs_dir}/\g<2>", text, flags=re.M)
    block = "\n".join(
        ["# --- NQX-S1: foundry I/O cells compared as black boxes (pins only) ---"]
        + [f'blank_circuit("{pattern}")' for pattern in BLACK_BOXES]
    )
    text, n_align = re.subn(r"^align\s*$", "align\n" + block, text, flags=re.M)
    if n_inc < 10 or n_align != 1:
        sys.exit(f"unexpected PDK deck layout: {n_inc} includes, {n_align} align statements")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        f"# GENERATED by scripts/make_lvs_deck.py from {lvs_dir / 'sg13g2.lvs'}\n" + text
    )
    print(f"wrote {out}: {n_inc} includes rewritten, black boxes: {', '.join(BLACK_BOXES)}")


if __name__ == "__main__":
    main()
