// GENERATED by tools/gen_params.py from model/nqx_s1/params.py -- do not edit.
// atan(2^-i) as a ZW-bit binary angle (full turn = 2^ZW).
function automatic [19:0] nqx_atan(input integer i);
    case (i)
         0: nqx_atan = 20'd131072;
         1: nqx_atan = 20'd77376;
         2: nqx_atan = 20'd40884;
         3: nqx_atan = 20'd20753;
         4: nqx_atan = 20'd10417;
         5: nqx_atan = 20'd5213;
         6: nqx_atan = 20'd2607;
         7: nqx_atan = 20'd1304;
         8: nqx_atan = 20'd652;
         9: nqx_atan = 20'd326;
        10: nqx_atan = 20'd163;
        11: nqx_atan = 20'd81;
        12: nqx_atan = 20'd41;
        13: nqx_atan = 20'd20;
        14: nqx_atan = 20'd10;
        15: nqx_atan = 20'd5;
        16: nqx_atan = 20'd3;
        17: nqx_atan = 20'd1;
        default: nqx_atan = 20'd0;
    endcase
endfunction
