// NQX-S1, DIM=32: flattened by tools/export_tinytapeout.py from nqx-silicon/rtl.
// Do not edit; regenerate instead.
/* verilator lint_off DECLFILENAME */
// Inlined, GENERATED by tools/gen_params.py from model/nqx_s1/params.py -- do not edit.
`ifndef NQX_S1_PARAMS_VH
`define NQX_S1_PARAMS_VH

`define NQX_DIM          32
`define NQX_LOG2_DIM     5
`define NQX_IN_W         16
`define NQX_FW           4
`define NQX_DW           23
`define NQX_GB           2
`define NQX_CW           27
`define NQX_ZW           20
`define NQX_NITER        18
`define NQX_KF           18
`define NQX_KINV         159188
`define NQX_STEPF        8
`define NQX_HB           3
`define NQX_NPAIRS       16
`define NQX_L3_STRIDE    8
`define NQX_PKT_BYTES    22
`define NQX_CORDIC_LAT   20

`define NQX_INC0_RESET  32'h61C88647
`define NQX_INC1_RESET  32'h9E3779B9
`define NQX_INC2_RESET  32'h00000000
`define NQX_CHIP_ID      32'h4E515831
`define NQX_VERSION      32'h00010000
`define NQX_PARAMS_WORD  32'h14121705

`endif

// ---- nqx_s1_top.sv -----------------------------------------------
// NQX-S1 top level (pad-facing ports of the digital block).
//
// 22 signal pins: clk, rst_n, in_bus[7:0], in_req, in_ack, out_bus[7:0],
// out_req, out_ack, busy.
`default_nettype none

module nqx_s1_top #(
    parameter integer ITER_CORDIC = 0
) (
    input  wire       clk,
    input  wire       rst_n,
    input  wire [7:0] in_bus,
    input  wire       in_req,
    output wire       in_ack,
    output wire [7:0] out_bus,
    output wire       out_req,
    input  wire       out_ack,
    output wire       busy
);
    // Asynchronous assert, synchronous de-assert.
    /* verilator lint_off SYNCASYNCNET */
    reg [1:0] rst_sync;
    /* verilator lint_on SYNCASYNCNET */
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) rst_sync <= 2'b00;
        else        rst_sync <= {rst_sync[0], 1'b1};
    end
    wire rst_n_s = rst_sync[1];

    wire [7:0] s_data;
    wire       s_valid;
    wire       s_ready;
    wire [7:0] m_data;
    wire       m_valid;
    wire       m_ready;

    nqx_s1_hsio u_io (
        .clk(clk), .rst_n(rst_n_s),
        .in_bus(in_bus), .in_req(in_req), .in_ack(in_ack),
        .out_bus(out_bus), .out_req(out_req), .out_ack(out_ack),
        .s_data(s_data), .s_valid(s_valid), .s_ready(s_ready),
        .m_data(m_data), .m_valid(m_valid), .m_ready(m_ready)
    );

    nqx_s1_core #(.ITER_CORDIC(ITER_CORDIC)) u_core (
        .clk(clk), .rst_n(rst_n_s),
        .in_data(s_data), .in_valid(s_valid), .in_ready(s_ready),
        .out_data(m_data), .out_valid(m_valid), .out_ready(m_ready),
        .busy(busy)
    );
endmodule

`default_nettype wire

// ---- nqx_s1_hsio.sv ----------------------------------------------
// Asynchronous 4-phase (return-to-zero) byte handshake <-> valid/ready stream.
//
// Host -> chip:  host drives in_bus and raises in_req; chip samples the bus,
//                raises in_ack; host drops in_req; chip drops in_ack.
// Chip -> host:  chip drives out_bus and raises out_req; host reads the bus,
//                raises out_ack; chip drops out_req; host drops out_ack.
//
// in_req and out_ack are asynchronous to clk and pass through two-flop
// synchronizers. in_bus is stable whenever in_req is high (bundled-data
// rule), so it is sampled without a synchronizer. out_bus is driven one clock
// before out_req rises, so the data pins settle before the request.
`default_nettype none

module nqx_s1_hsio (
    input  wire       clk,
    input  wire       rst_n,
    // pins
    input  wire [7:0] in_bus,
    input  wire       in_req,
    output reg        in_ack,
    output reg  [7:0] out_bus,
    output reg        out_req,
    input  wire       out_ack,
    // core side
    output reg  [7:0] s_data,
    output reg        s_valid,
    input  wire       s_ready,
    input  wire [7:0] m_data,
    input  wire       m_valid,
    output wire       m_ready
);
    reg [1:0] req_sync;
    reg [1:0] ack_sync;
    wire req_s = req_sync[1];
    wire ack_s = ack_sync[1];

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            req_sync <= 2'b00;
            ack_sync <= 2'b00;
        end else begin
            req_sync <= {req_sync[0], in_req};
            ack_sync <= {ack_sync[0], out_ack};
        end
    end

    // ---------------------------------------------------------- inbound
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            in_ack  <= 1'b0;
            s_valid <= 1'b0;
            s_data  <= 8'd0;
        end else begin
            if (s_valid && s_ready)
                s_valid <= 1'b0;
            if (req_s && !in_ack && !s_valid) begin
                s_data  <= in_bus;
                s_valid <= 1'b1;
                in_ack  <= 1'b1;
            end else if (!req_s && in_ack) begin
                in_ack <= 1'b0;
            end
        end
    end

    // --------------------------------------------------------- outbound
    reg out_pend;
    assign m_ready = !out_req && !out_pend && !ack_s;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            out_req  <= 1'b0;
            out_pend <= 1'b0;
            out_bus  <= 8'd0;
        end else if (out_pend) begin
            out_pend <= 1'b0;
            out_req  <= 1'b1;
        end else if (out_req) begin
            if (ack_s)
                out_req <= 1'b0;
        end else if (m_valid && !ack_s) begin
            out_bus  <= m_data;
            out_pend <= 1'b1;
        end
    end
endmodule

`default_nettype wire

// ---- nqx_s1_core.sv ----------------------------------------------
// NQX-S1 core: command decoder, micro-op sequencer, CSRs, vector register,
// CORDIC, quantizer and dequantizer. Byte-stream interface with valid/ready
// handshake on both sides. Behaviour is defined by model/nqx_s1/core.py.
`default_nettype none

module nqx_s1_core #(
    // 0: pipelined CORDIC, one pair per clock (default).
    // 1: iterative CORDIC, one pair per NITER+1 clocks, much smaller.
    // Results are bit-identical; only the cycle counts differ.
    parameter integer ITER_CORDIC = 0
) (
    input  wire       clk,
    input  wire       rst_n,
    input  wire [7:0] in_data,
    input  wire       in_valid,
    output wire       in_ready,
    output wire [7:0] out_data,
    output wire       out_valid,
    input  wire       out_ready,
    output wire       busy
);
    localparam integer DIM  = `NQX_DIM;
    localparam integer L    = `NQX_LOG2_DIM;
    localparam integer DW   = `NQX_DW;
    localparam integer ZW   = `NQX_ZW;
    localparam integer FW   = `NQX_FW;
    localparam integer HB   = `NQX_HB;
    localparam integer SW   = `NQX_DW + `NQX_STEPF - 4;
    localparam integer S3   = `NQX_L3_STRIDE;
    localparam integer S3B  = $clog2(S3);
    localparam integer NP   = `NQX_NPAIRS;
    localparam integer HBW  = 8 * HB;

    localparam [L-1:0] S3V      = L'(S3);
    localparam [L-1:0] KMAX_ADJ = L'(NP - 1);
    localparam [L-1:0] KMAX_SH  = L'(NP - 2);
    localparam [L-1:0] KMAX_L3  = L'(DIM - 1);
    localparam [L-1:0] KLAST_EL = L'(DIM - 1);
    localparam [2:0]   HB_LAST  = 3'(HB - 1);
    localparam [2:0]   HDR_LAST = 3'(2 * HB - 1);

    // ------------------------------------------------------------ opcodes
    localparam [7:0] OP_NOP = 8'h00, OP_LDV = 8'h01, OP_STV = 8'h02, OP_STVR = 8'h03,
                     OP_GVNS = 8'h10, OP_GVNS_INV = 8'h11, OP_POLAR = 8'h20,
                     OP_IPOLAR = 8'h21, OP_QUANT = 8'h30, OP_DEQUANT = 8'h31,
                     OP_ENC = 8'h60, OP_DEC = 8'h61, OP_SYNC = 8'h70, OP_CSRW = 8'h71,
                     OP_CSRR = 8'h72;

    localparam [7:0] SYNC_BYTE = 8'hA5;

    // ---------------------------------------------------------- micro-ops
    localparam [2:0] U_LDV = 3'd0, U_STV = 3'd1, U_STVR = 3'd2, U_ROT = 3'd3,
                     U_POLAR = 3'd4, U_IPOLAR = 3'd5, U_QUANT = 3'd6, U_DEQUANT = 3'd7;

    localparam [1:0] M_NONE = 2'd0, M_ENC = 2'd1, M_DEC = 2'd2;

    // ------------------------------------------------------------- states
    localparam [4:0] S_IDLE = 5'd0, S_ARG = 5'd1, S_CSRW_A = 5'd2, S_CSRW_D = 5'd3,
                     S_CSRR_A = 5'd4, S_EMIT = 5'd5, S_LAUNCH = 5'd6, S_NEXT = 5'd7,
                     S_LDV = 5'd8, S_STV = 5'd9, S_ISSUE = 5'd10, S_DRAIN = 5'd11,
                     S_QHDR = 5'd12, S_QRD = 5'd13, S_QC1 = 5'd14, S_QC2 = 5'd15,
                     S_DHDR = 5'd16, S_DPREP = 5'd17, S_DDIV = 5'd18, S_DBYTE = 5'd19,
                     S_DWR = 5'd20, S_CSRR_L = 5'd21;

    // --------------------------------------------------------- CSR space
    localparam [7:0] CSR_ID = 8'h00, CSR_VERSION = 8'h01, CSR_PARAMS = 8'h02,
                     CSR_CTRL = 8'h03, CSR_STATUS = 8'h04, CSR_INC0 = 8'h05,
                     CSR_INC1 = 8'h06, CSR_INC2 = 8'h07, CSR_RMIN = 8'h08,
                     CSR_RMAX = 8'h09, CSR_SCRATCH = 8'h0A, CSR_FEATURES = 8'h0B,
                     CSR_CYCLES = 8'h10,
                     CSR_BUSY = 8'h11, CSR_CORDIC = 8'h12, CSR_ENC = 8'h13,
                     CSR_DEC = 8'h14;

    // Macro sequences: ENC = LDV, ROT0, ROT1, ROT2, POLAR, QUANT
    //                  DEC = DEQUANT, IPOLAR, ROT2^-1, ROT1^-1, ROT0^-1, STV
    function automatic [5:0] macro_uop(input [1:0] m, input [2:0] step);
        // returns {uop[2:0], layer[1:0], inv}
        begin
            if (m == M_ENC) begin
                case (step)
                    3'd0:    macro_uop = {U_LDV, 2'd0, 1'b0};
                    3'd1:    macro_uop = {U_ROT, 2'd0, 1'b0};
                    3'd2:    macro_uop = {U_ROT, 2'd1, 1'b0};
                    3'd3:    macro_uop = {U_ROT, 2'd2, 1'b0};
                    3'd4:    macro_uop = {U_POLAR, 2'd0, 1'b0};
                    default: macro_uop = {U_QUANT, 2'd0, 1'b0};
                endcase
            end else begin
                case (step)
                    3'd0:    macro_uop = {U_DEQUANT, 2'd0, 1'b0};
                    3'd1:    macro_uop = {U_IPOLAR, 2'd0, 1'b0};
                    3'd2:    macro_uop = {U_ROT, 2'd2, 1'b1};
                    3'd3:    macro_uop = {U_ROT, 2'd1, 1'b1};
                    3'd4:    macro_uop = {U_ROT, 2'd0, 1'b1};
                    default: macro_uop = {U_STV, 2'd0, 1'b0};
                endcase
            end
        end
    endfunction

    // --------------------------------------------------------- registers
    reg [4:0]  state;
    reg [2:0]  uop;
    reg [1:0]  layer;
    reg        inv;
    reg [1:0]  macro;
    reg [2:0]  mstep;

    reg [L-1:0] k;       // pair / element counter
    reg [2:0]   b;       // byte counter within an element or header
    reg [7:0]   lo;      // low byte of an LDV element
    reg [31:0]  acc;     // phase accumulator
    reg         first;   // first radius of a POLAR pass

    reg [7:0]   caddr;
    /* verilator lint_off UNUSEDSIGNAL */
    reg [31:0]  wshift;     // [7:0] is shifted out before the word completes
    /* verilator lint_on UNUSEDSIGNAL */
    reg [31:0]  oshift;
    reg [2:0]   ocnt;

    reg [7:0]   obuf;
    reg         obuf_v;

    reg [31:0]  inc0, inc1, inc2;
    reg         refine;
    reg         st_illegal, st_sat;
    reg [DW-1:0] rmin, rmax;
    reg [31:0]  scratch;
    reg [31:0]  cnt_cycles, cnt_busy, cnt_cordic, cnt_enc, cnt_dec;

    reg signed [DW:0] qd;
    reg [ZW-1:0]      qt;
    reg [2:0]         qq;
    reg [DW-1:0]      qrng;

    reg [8*2*HB-1:0]  hdr;
    wire [31:0]       wword = {in_data, wshift[31:8]};
    wire [HBW-1:0]    rmin_ext = HBW'(rmin);
    wire [HBW-1:0]    rmax_ext = HBW'(rmax);
    wire [8*2*HB-1:0] qhdr     = {rmax_ext, rmin_ext};
    reg [DW-1:0]      drmin;
    reg [7:0]         pk;

    // ------------------------------------------------------ handshakes
    assign in_ready = (state == S_IDLE) || (state == S_ARG) || (state == S_CSRW_A) ||
                      (state == S_CSRW_D) || (state == S_CSRR_A) || (state == S_LDV) ||
                      (state == S_DHDR) || (state == S_DBYTE);
    wire in_fire  = in_valid && in_ready;
    wire obuf_free = !obuf_v || out_ready;

    assign out_data  = obuf;
    assign out_valid = obuf_v;
    assign busy      = state != S_IDLE;

    // --------------------------------------------------- selected phase inc
    wire [31:0] inc_sel = (layer == 2'd0) ? inc0 : (layer == 2'd1) ? inc1 : inc2;

    // ------------------------------------------------------ pair addressing
    wire [L-1:0] k2    = {k[L-2:0], 1'b0};
    wire [L-1:0] i_adj = k2;
    wire [L-1:0] i_sh  = {k[L-2:0], 1'b1};
    reg  [L-1:0] pi, pj;
    reg          pvalid;
    reg  [L-1:0] kmax;

    always @(*) begin
        pvalid = 1'b1;
        if (uop == U_ROT && layer == 2'd1) begin
            pi = i_sh;
            pj = i_sh + 1'b1;
            kmax = KMAX_SH;
        end else if (uop == U_ROT && layer == 2'd2) begin
            pi = k;
            pj = k + S3V;
            pvalid = ~k[S3B];
            kmax = KMAX_L3;
        end else begin
            pi = i_adj;
            pj = i_adj + 1'b1;
            kmax = KMAX_ADJ;
        end
    end

    // --------------------------------------------------------- register file
    reg  [L-1:0]         ra, rb;
    wire signed [DW-1:0] rda, rdb;
    reg                  wea, web;
    reg  [L-1:0]         wa, wb;
    reg  signed [DW-1:0] wda, wdb;

    nqx_s1_rf u_rf (
        .clk(clk), .rst_n(rst_n), .ra(ra), .rb(rb), .rda(rda), .rdb(rdb),
        .wea(wea), .wa(wa), .wda(wda), .web(web), .wb(wb), .wdb(wdb)
    );

    // ---------------------------------------------------------------- CORDIC
    wire [ZW-1:0] zr    = acc[31:32-ZW] + {{(ZW-1){1'b0}}, acc[31-ZW]};
    wire [ZW-1:0] zphase = inv ? -zr : zr;

    wire                 c_ready;
    wire                 c_in_valid = (state == S_ISSUE) && pvalid && c_ready;
    wire                 c_in_vec   = uop == U_POLAR;
    wire signed [DW-1:0] c_in_y     = (uop == U_IPOLAR) ? {DW{1'b0}} : rdb;
    wire        [ZW-1:0] c_in_z     = (uop == U_ROT) ? zphase :
                                      (uop == U_IPOLAR) ? rdb[ZW-1:0] : {ZW{1'b0}};

    wire                 c_out_valid;
    wire signed [DW-1:0] c_out_x, c_out_y;
    wire        [ZW-1:0] c_out_z;
    wire                 c_out_sat;
    wire [2*L-1:0]       c_out_tag;
    wire                 c_busy;

    generate
        if (ITER_CORDIC != 0) begin : g_cordic_iter
            /* verilator lint_off UNUSEDSIGNAL */
            wire it_busy;
            /* verilator lint_on UNUSEDSIGNAL */
            nqx_s1_cordic_iter #(.TAG_W(2*L)) u_cordic (
                .clk(clk), .rst_n(rst_n),
                .in_valid(c_in_valid), .in_ready(c_ready), .in_vec(c_in_vec),
                .in_x(rda), .in_y(c_in_y), .in_z(c_in_z), .in_tag({pi, pj}),
                .out_valid(c_out_valid), .out_x(c_out_x), .out_y(c_out_y), .out_z(c_out_z),
                .out_sat(c_out_sat), .out_tag(c_out_tag), .busy(it_busy)
            );
        end else begin : g_cordic_pipe
            assign c_ready = 1'b1;
            nqx_s1_cordic #(.TAG_W(2*L)) u_cordic (
                .clk(clk), .rst_n(rst_n),
                .in_valid(c_in_valid), .in_vec(c_in_vec), .in_x(rda), .in_y(c_in_y),
                .in_z(c_in_z), .in_tag({pi, pj}),
                .out_valid(c_out_valid), .out_x(c_out_x), .out_y(c_out_y), .out_z(c_out_z),
                .out_sat(c_out_sat), .out_tag(c_out_tag)
            );
        end
    endgenerate

    // Pipeline occupancy for the drain phase.
    reg [5:0] inflight;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            inflight <= 6'd0;
        else
            inflight <= inflight + {5'd0, c_in_valid} - {5'd0, c_out_valid};
    end
    assign c_busy = (inflight != 6'd0);

    // ------------------------------------------------------------- quantizer
    wire [2:0] rq;
    wire       rs;
    wire [2:0] tq3;
    wire       ts;

    nqx_s1_rcode u_rcode (.d(qd), .rng(qrng), .q(rq));
    nqx_s1_rsign u_rsign (.d(qd), .rng(qrng), .q(qq), .s(rs));
    nqx_s1_tcode u_tcode (.t(qt), .q(tq3), .s(ts));

    // ----------------------------------------------------------- dequantizer
    localparam [DW-1:0] RLIM = (1 << (DW - 1)) - 1;

    wire [DW-1:0] h_rmin = hdr[DW-1:0];
    wire [DW-1:0] h_rmax = hdr[8*HB +: DW];
    wire          h_sat  = (h_rmin > RLIM) || (h_rmax > RLIM);
    wire [DW-1:0] c_rmin = (h_rmin > RLIM) ? RLIM : h_rmin;
    wire [DW-1:0] c_rmax = (h_rmax > RLIM) ? RLIM : h_rmax;
    wire [DW-1:0] c_rng  = (c_rmax > c_rmin) ? c_rmax - c_rmin : {DW{1'b0}};

    wire          div_start = state == S_DPREP;
    wire [SW-1:0] step;
    wire          div_busy;

    nqx_s1_div28 u_div (
        .clk(clk), .rst_n(rst_n), .start(div_start), .rng(c_rng), .step(step), .busy(div_busy)
    );

    wire signed [DW-1:0] dq_r;
    wire        [ZW-1:0] dq_t;
    wire                 dq_sat;

    nqx_s1_qdec u_qdec (
        .pk(pk), .rmin(drmin), .step(step), .refine(refine), .r(dq_r), .t(dq_t), .sat(dq_sat)
    );

    // ------------------------------------------------------ store rounding
    wire signed [DW:0]    st_rnd = {rda[DW-1], rda} + (1 << (FW - 1));
    /* verilator lint_off UNUSEDSIGNAL */
    wire signed [DW:0]    st_shr = st_rnd >>> FW;
    /* verilator lint_on UNUSEDSIGNAL */
    wire signed [DW-FW:0] st_val = st_shr[DW-FW:0];
    wire st_hi = st_val > 32767;
    wire st_lo = st_val < -32768;
    wire [15:0] st16 = st_hi ? 16'h7FFF : st_lo ? 16'h8000 : st_val[15:0];
    wire signed [HBW-1:0] st_raw = HBW'(rda);

    // ------------------------------------------------------- CSR read mux
    reg [31:0] csr_rdata;
    always @(*) begin
        case (caddr)
            CSR_ID:      csr_rdata = `NQX_CHIP_ID;
            CSR_VERSION: csr_rdata = `NQX_VERSION;
            CSR_PARAMS:  csr_rdata = `NQX_PARAMS_WORD;
            CSR_CTRL:    csr_rdata = {31'd0, refine};
            CSR_STATUS:  csr_rdata = {30'd0, st_sat, st_illegal};
            CSR_INC0:    csr_rdata = inc0;
            CSR_INC1:    csr_rdata = inc1;
            CSR_INC2:    csr_rdata = inc2;
            CSR_RMIN:    csr_rdata = {{(32-DW){1'b0}}, rmin};
            CSR_RMAX:    csr_rdata = {{(32-DW){1'b0}}, rmax};
            CSR_SCRATCH: csr_rdata = scratch;
            CSR_FEATURES: csr_rdata = {31'd0, ITER_CORDIC != 0};
            CSR_CYCLES:  csr_rdata = cnt_cycles;
            CSR_BUSY:    csr_rdata = cnt_busy;
            CSR_CORDIC:  csr_rdata = cnt_cordic;
            CSR_ENC:     csr_rdata = cnt_enc;
            CSR_DEC:     csr_rdata = cnt_dec;
            default:     csr_rdata = 32'd0;
        endcase
    end

    // --------------------------------------------- RF port and write muxing
    always @(*) begin
        ra  = pi;
        rb  = pj;
        wea = 1'b0;
        web = 1'b0;
        wa  = {L{1'b0}};
        wb  = {L{1'b0}};
        wda = {DW{1'b0}};
        wdb = {DW{1'b0}};
        case (state)
            S_STV:  ra = k;
            S_QRD: begin
                ra = k2;
                rb = k2 + 1'b1;
            end
            default: ;
        endcase
        if (c_out_valid) begin
            wea = 1'b1;
            wa  = c_out_tag[2*L-1:L];
            wda = c_out_x;
            web = 1'b1;
            wb  = c_out_tag[L-1:0];
            wdb = (uop == U_POLAR) ? {{(DW-ZW){c_out_z[ZW-1]}}, c_out_z} : c_out_y;
        end else if (state == S_LDV && in_fire && b[0]) begin
            wea = 1'b1;
            wa  = k;
            wda = {{(DW-16-FW){in_data[7]}}, in_data, lo, {FW{1'b0}}};
        end else if (state == S_DWR) begin
            wea = 1'b1;
            wa  = k2;
            wda = dq_r;
            web = 1'b1;
            wb  = k2 + 1'b1;
            wdb = {{(DW-ZW){dq_t[ZW-1]}}, dq_t};
        end
    end

    // --------------------------------------------------------- main FSM
    wire last_k = (k == kmax);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state      <= S_IDLE;
            uop        <= U_LDV;
            layer      <= 2'd0;
            inv        <= 1'b0;
            macro      <= M_NONE;
            mstep      <= 3'd0;
            k          <= {L{1'b0}};
            b          <= 3'd0;
            lo         <= 8'd0;
            acc        <= 32'd0;
            first      <= 1'b0;
            caddr      <= 8'd0;
            wshift     <= 32'd0;
            oshift     <= 32'd0;
            ocnt       <= 3'd0;
            obuf       <= 8'd0;
            obuf_v     <= 1'b0;
            inc0       <= `NQX_INC0_RESET;
            inc1       <= `NQX_INC1_RESET;
            inc2       <= `NQX_INC2_RESET;
            refine     <= 1'b1;
            st_illegal <= 1'b0;
            st_sat     <= 1'b0;
            rmin       <= {DW{1'b0}};
            rmax       <= {DW{1'b0}};
            scratch    <= 32'd0;
            cnt_cycles <= 32'd0;
            cnt_busy   <= 32'd0;
            cnt_cordic <= 32'd0;
            cnt_enc    <= 32'd0;
            cnt_dec    <= 32'd0;
            qd         <= {(DW+1){1'b0}};
            qt         <= {ZW{1'b0}};
            qq         <= 3'd0;
            qrng       <= {DW{1'b0}};
            hdr        <= {(16*HB){1'b0}};
            drmin      <= {DW{1'b0}};
            pk         <= 8'd0;
        end else begin
            cnt_cycles <= cnt_cycles + 1'b1;
            if (state != S_IDLE)
                cnt_busy <= cnt_busy + 1'b1;
            if (c_in_valid)
                cnt_cordic <= cnt_cordic + 1'b1;

            if (obuf_v && out_ready)
                obuf_v <= 1'b0;

            // CORDIC write-back side effects
            if (c_out_valid) begin
                if (c_out_sat)
                    st_sat <= 1'b1;
                if (uop == U_POLAR) begin
                    if (first) begin
                        rmin  <= c_out_x;
                        rmax  <= c_out_x;
                        first <= 1'b0;
                    end else begin
                        if (c_out_x < $signed(rmin)) rmin <= c_out_x;
                        if (c_out_x > $signed(rmax)) rmax <= c_out_x;
                    end
                end
            end

            case (state)
                // ------------------------------------------------ dispatch
                S_IDLE: if (in_fire) begin
                    macro <= M_NONE;
                    case (in_data)
                        OP_NOP: ;
                        OP_LDV:     begin uop <= U_LDV;     state <= S_LAUNCH; end
                        OP_STV:     begin uop <= U_STV;     state <= S_LAUNCH; end
                        OP_STVR:    begin uop <= U_STVR;    state <= S_LAUNCH; end
                        OP_POLAR:   begin uop <= U_POLAR;   state <= S_LAUNCH; end
                        OP_IPOLAR:  begin uop <= U_IPOLAR;  state <= S_LAUNCH; end
                        OP_QUANT:   begin uop <= U_QUANT;   state <= S_LAUNCH; end
                        OP_DEQUANT: begin uop <= U_DEQUANT; state <= S_LAUNCH; end
                        OP_GVNS:     begin inv <= 1'b0; state <= S_ARG; end
                        OP_GVNS_INV: begin inv <= 1'b1; state <= S_ARG; end
                        OP_ENC: begin
                            macro <= M_ENC;
                            mstep <= 3'd0;
                            {uop, layer, inv} <= macro_uop(M_ENC, 3'd0);
                            state <= S_LAUNCH;
                        end
                        OP_DEC: begin
                            macro <= M_DEC;
                            mstep <= 3'd0;
                            {uop, layer, inv} <= macro_uop(M_DEC, 3'd0);
                            state <= S_LAUNCH;
                        end
                        OP_SYNC: begin
                            oshift <= {24'd0, SYNC_BYTE};
                            ocnt   <= 3'd1;
                            state  <= S_EMIT;
                        end
                        OP_CSRW: state <= S_CSRW_A;
                        OP_CSRR: state <= S_CSRR_A;
                        default: st_illegal <= 1'b1;
                    endcase
                end

                S_ARG: if (in_fire) begin
                    if (in_data > 8'd2) begin
                        st_illegal <= 1'b1;
                        state      <= S_IDLE;
                    end else begin
                        layer <= in_data[1:0];
                        uop   <= U_ROT;
                        state <= S_LAUNCH;
                    end
                end

                // --------------------------------------------------- CSRs
                S_CSRW_A: if (in_fire) begin
                    caddr <= in_data;
                    b     <= 3'd0;
                    state <= S_CSRW_D;
                end

                S_CSRW_D: if (in_fire) begin
                    wshift <= wword;
                    b      <= b + 1'b1;
                    if (b == 3'd3) begin
                        case (caddr)
                            CSR_CTRL:    refine <= wword[0];
                            CSR_STATUS: begin
                                if (wword[0]) st_illegal <= 1'b0;
                                if (wword[1]) st_sat     <= 1'b0;
                            end
                            CSR_INC0:    inc0    <= wword;
                            CSR_INC1:    inc1    <= wword;
                            CSR_INC2:    inc2    <= wword;
                            CSR_SCRATCH: scratch <= wword;
                            default: ;
                        endcase
                        state <= S_IDLE;
                    end
                end

                S_CSRR_A: if (in_fire) begin
                    caddr <= in_data;
                    state <= S_CSRR_L;
                end

                S_CSRR_L: begin
                    oshift <= csr_rdata;
                    ocnt   <= 3'd4;
                    state  <= S_EMIT;
                end

                S_EMIT: if (obuf_free) begin
                    obuf   <= oshift[7:0];
                    obuf_v <= 1'b1;
                    oshift <= {8'd0, oshift[31:8]};
                    ocnt   <= ocnt - 1'b1;
                    if (ocnt == 3'd1)
                        state <= S_IDLE;
                end

                // ------------------------------------------- uop launcher
                S_LAUNCH: begin
                    k <= {L{1'b0}};
                    b <= 3'd0;
                    case (uop)
                        U_LDV:     state <= S_LDV;
                        U_STV,
                        U_STVR:    state <= S_STV;
                        U_ROT: begin
                            acc   <= inc_sel;
                            state <= (inc_sel == 32'd0) ? S_NEXT : S_ISSUE;
                        end
                        U_POLAR: begin
                            first <= 1'b1;
                            state <= S_ISSUE;
                        end
                        U_IPOLAR:  state <= S_ISSUE;
                        U_QUANT: begin
                            qrng  <= rmax - rmin;
                            state <= S_QHDR;
                        end
                        default:   state <= S_DHDR;
                    endcase
                end

                S_NEXT: begin
                    if (macro != M_NONE && mstep != 3'd5) begin
                        mstep <= mstep + 1'b1;
                        {uop, layer, inv} <= macro_uop(macro, mstep + 1'b1);
                        state <= S_LAUNCH;
                    end else begin
                        macro <= M_NONE;
                        state <= S_IDLE;
                    end
                end

                // ---------------------------------------------- load/store
                S_LDV: if (in_fire) begin
                    if (!b[0]) begin
                        lo <= in_data;
                        b  <= 3'd1;
                    end else begin
                        b <= 3'd0;
                        k <= k + 1'b1;
                        if (k == KLAST_EL)
                            state <= S_NEXT;
                    end
                end

                S_STV: if (obuf_free) begin
                    obuf_v <= 1'b1;
                    if (uop == U_STV) begin
                        obuf <= b[0] ? st16[15:8] : st16[7:0];
                        if (!b[0] && (st_hi || st_lo))
                            st_sat <= 1'b1;
                    end else begin
                        obuf <= st_raw[8*b +: 8];
                    end
                    if ((uop == U_STV && b == 3'd1) || (uop == U_STVR && b == HB_LAST)) begin
                        b <= 3'd0;
                        k <= k + 1'b1;
                        if (k == KLAST_EL)
                            state <= S_NEXT;
                    end else begin
                        b <= b + 1'b1;
                    end
                end

                // ------------------------------------------ CORDIC passes
                S_ISSUE: if (c_ready || !pvalid) begin
                    k   <= k + 1'b1;
                    acc <= acc + inc_sel;
                    if (last_k)
                        state <= S_DRAIN;
                end

                S_DRAIN: if (!c_busy && !c_out_valid)
                    state <= S_NEXT;

                // ------------------------------------------------ quantize
                S_QHDR: if (obuf_free) begin
                    obuf_v <= 1'b1;
                    obuf   <= qhdr[8*b +: 8];
                    b      <= b + 1'b1;
                    if (b == HDR_LAST)
                        state <= S_QRD;
                end

                S_QRD: begin
                    qd    <= $signed({rda[DW-1], rda}) - $signed({1'b0, rmin});
                    qt    <= rdb[ZW-1:0];
                    state <= S_QC1;
                end

                S_QC1: begin
                    qq    <= rq;
                    state <= S_QC2;
                end

                S_QC2: if (obuf_free) begin
                    obuf_v <= 1'b1;
                    obuf   <= {ts, tq3, rs, qq};
                    k      <= k + 1'b1;
                    if (k == KMAX_ADJ) begin
                        cnt_enc <= cnt_enc + 1'b1;
                        state   <= S_NEXT;
                    end else begin
                        state <= S_QRD;
                    end
                end

                // ---------------------------------------------- dequantize
                S_DHDR: if (in_fire) begin
                    hdr <= {in_data, hdr[8*2*HB-1:8]};
                    b   <= b + 1'b1;
                    if (b == HDR_LAST)
                        state <= S_DPREP;
                end

                S_DPREP: begin
                    drmin <= c_rmin;
                    if (h_sat)
                        st_sat <= 1'b1;
                    state <= S_DDIV;
                end

                S_DDIV: if (!div_busy)
                    state <= S_DBYTE;

                S_DBYTE: if (in_fire) begin
                    pk    <= in_data;
                    state <= S_DWR;
                end

                S_DWR: begin
                    if (dq_sat)
                        st_sat <= 1'b1;
                    k <= k + 1'b1;
                    if (k == KMAX_ADJ) begin
                        cnt_dec <= cnt_dec + 1'b1;
                        state   <= S_NEXT;
                    end else begin
                        state <= S_DBYTE;
                    end
                end

                default: state <= S_IDLE;
            endcase
        end
    end

endmodule

`default_nettype wire

// ---- nqx_s1_cordic.sv --------------------------------------------
// NQX-S1 pipelined CORDIC.
//
// Mode in_vec = 0 (rotation):  (x, y) rotated by angle z.
// Mode in_vec = 1 (vectoring): (x, y) -> (r, theta); r on out_x, theta on out_z.
//
// Angles are ZW-bit binary angles (full turn = 2^ZW, so mod-2*pi is free).
// Latency is NITER + 2 cycles, one new operand pair per cycle.
// Bit-exact with model/nqx_s1/cordic.py.
`default_nettype none

module nqx_s1_cordic #(
    parameter integer TAG_W = 14
) (
    input  wire                        clk,
    input  wire                        rst_n,
    input  wire                        in_valid,
    input  wire                        in_vec,
    input  wire signed [`NQX_DW-1:0]   in_x,
    input  wire signed [`NQX_DW-1:0]   in_y,
    input  wire        [`NQX_ZW-1:0]   in_z,
    input  wire        [TAG_W-1:0]     in_tag,
    output reg                         out_valid,
    output reg  signed [`NQX_DW-1:0]   out_x,
    output reg  signed [`NQX_DW-1:0]   out_y,
    output reg         [`NQX_ZW-1:0]   out_z,
    output reg                         out_sat,
    output reg         [TAG_W-1:0]     out_tag
);

    localparam integer DW = `NQX_DW;
    localparam integer CW = `NQX_CW;
    localparam integer ZW = `NQX_ZW;
    localparam integer GB = `NQX_GB;
    localparam integer N  = `NQX_NITER;
    localparam integer KF = `NQX_KF;
    localparam integer SH = KF + GB;
    localparam integer PW = CW + KF + 1;
function automatic [19:0] nqx_atan(input integer i);
    case (i)
         0: nqx_atan = 20'd131072;
         1: nqx_atan = 20'd77376;
         2: nqx_atan = 20'd40884;
         3: nqx_atan = 20'd20753;
         4: nqx_atan = 20'd10417;
         5: nqx_atan = 20'd5213;
         6: nqx_atan = 20'd2607;
         7: nqx_atan = 20'd1304;
         8: nqx_atan = 20'd652;
         9: nqx_atan = 20'd326;
        10: nqx_atan = 20'd163;
        11: nqx_atan = 20'd81;
        12: nqx_atan = 20'd41;
        13: nqx_atan = 20'd20;
        14: nqx_atan = 20'd10;
        15: nqx_atan = 20'd5;
        16: nqx_atan = 20'd3;
        17: nqx_atan = 20'd1;
        default: nqx_atan = 20'd0;
    endcase
endfunction
    // Stage outputs, stage s drives slice s.
    wire [CW*(N+1)-1:0]    xs;
    wire [CW*(N+1)-1:0]    ys;
    wire [ZW*(N+1)-1:0]    zs;
    wire [N:0]             vs;
    wire [N:0]             ms;
    wire [TAG_W*(N+1)-1:0] ts;

    // ---------------------------------------------------------- stage 0 ----
    // Quadrant pre-rotation so that the residual angle lies in [-90, 90).
    wire signed [CW-1:0] ext_x = {{(CW-DW-GB){in_x[DW-1]}}, in_x, {GB{1'b0}}};
    wire signed [CW-1:0] ext_y = {{(CW-DW-GB){in_y[DW-1]}}, in_y, {GB{1'b0}}};

    wire rot_flip = in_z[ZW-1] ^ in_z[ZW-2];
    wire vec_flip = in_x[DW-1];
    wire flip     = in_vec ? vec_flip : rot_flip;

    wire [ZW-1:0] z_rot = {in_z[ZW-1] ^ rot_flip, in_z[ZW-2:0]};
    wire [ZW-1:0] z_vec = {vec_flip, {(ZW-1){1'b0}}};

    reg              v0_q;
    reg [CW-1:0]     x0_q;
    reg [CW-1:0]     y0_q;
    reg [ZW-1:0]     z0_q;
    reg              m0_q;
    reg [TAG_W-1:0]  t0_q;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            v0_q <= 1'b0;
            x0_q <= {CW{1'b0}};
            y0_q <= {CW{1'b0}};
            z0_q <= {ZW{1'b0}};
            m0_q <= 1'b0;
            t0_q <= {TAG_W{1'b0}};
        end else begin
            v0_q <= in_valid;
            x0_q <= flip ? -ext_x : ext_x;
            y0_q <= flip ? -ext_y : ext_y;
            z0_q <= in_vec ? z_vec : z_rot;
            m0_q <= in_vec;
            t0_q <= in_tag;
        end
    end

    assign vs[0]            = v0_q;
    assign xs[CW-1:0]       = x0_q;
    assign ys[CW-1:0]       = y0_q;
    assign zs[ZW-1:0]       = z0_q;
    assign ms[0]            = m0_q;
    assign ts[TAG_W-1:0]    = t0_q;

    // ------------------------------------------------------- iterations ----
    genvar s;
    generate
        for (s = 0; s < N; s = s + 1) begin : g_iter
            wire signed [CW-1:0] x = xs[s*CW +: CW];
            wire signed [CW-1:0] y = ys[s*CW +: CW];
            wire        [ZW-1:0] z = zs[s*ZW +: ZW];
            wire signed [CW-1:0] xsh = x >>> s;
            wire signed [CW-1:0] ysh = y >>> s;
            wire          d = ms[s] ? y[CW-1] : ~z[ZW-1];
            wire [ZW-1:0] a = nqx_atan(s);

            reg             v_q;
            reg [CW-1:0]    x_q;
            reg [CW-1:0]    y_q;
            reg [ZW-1:0]    z_q;
            reg             m_q;
            reg [TAG_W-1:0] t_q;

            always @(posedge clk or negedge rst_n) begin
                if (!rst_n) begin
                    v_q <= 1'b0;
                    x_q <= {CW{1'b0}};
                    y_q <= {CW{1'b0}};
                    z_q <= {ZW{1'b0}};
                    m_q <= 1'b0;
                    t_q <= {TAG_W{1'b0}};
                end else begin
                    v_q <= vs[s];
                    x_q <= d ? x - ysh : x + ysh;
                    y_q <= d ? y + xsh : y - xsh;
                    z_q <= d ? z - a : z + a;
                    m_q <= ms[s];
                    t_q <= ts[s*TAG_W +: TAG_W];
                end
            end

            assign vs[s+1]                  = v_q;
            assign xs[(s+1)*CW +: CW]       = x_q;
            assign ys[(s+1)*CW +: CW]       = y_q;
            assign zs[(s+1)*ZW +: ZW]       = z_q;
            assign ms[s+1]                  = m_q;
            assign ts[(s+1)*TAG_W +: TAG_W] = t_q;
        end
    endgenerate

    // ---------------------------------------------- gain compensation ----
    wire signed [CW-1:0] xn   = xs[N*CW +: CW];
    wire signed [CW-1:0] yn   = ys[N*CW +: CW];
    wire signed [KF:0]   kinv = `NQX_KINV;
    wire signed [PW-1:0] rnd  = 1 <<< (SH-1);

    /* verilator lint_off UNUSEDSIGNAL */
    wire signed [PW-1:0]    px = xn * kinv + rnd;   // low SH bits are rounded off
    wire signed [PW-1:0]    py = yn * kinv + rnd;
    /* verilator lint_on UNUSEDSIGNAL */
    wire signed [PW-SH-1:0] cx = px[PW-1:SH];
    wire signed [PW-SH-1:0] cy = py[PW-1:SH];

    localparam signed [PW-SH-1:0] HI = (1 <<< (DW-1)) - 1;
    localparam signed [PW-SH-1:0] LO = -(1 <<< (DW-1));

    wire sx_hi = cx > HI;
    wire sx_lo = cx < LO;
    wire sy_hi = cy > HI;
    wire sy_lo = cy < LO;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            out_valid <= 1'b0;
            out_x     <= {DW{1'b0}};
            out_y     <= {DW{1'b0}};
            out_z     <= {ZW{1'b0}};
            out_sat   <= 1'b0;
            out_tag   <= {TAG_W{1'b0}};
        end else begin
            out_valid <= vs[N];
            out_x     <= sx_hi ? HI[DW-1:0] : sx_lo ? LO[DW-1:0] : cx[DW-1:0];
            out_y     <= sy_hi ? HI[DW-1:0] : sy_lo ? LO[DW-1:0] : cy[DW-1:0];
            out_z     <= zs[N*ZW +: ZW];
            out_sat   <= sx_hi | sx_lo | (~ms[N] & (sy_hi | sy_lo));
            out_tag   <= ts[N*TAG_W +: TAG_W];
        end
    end

endmodule

`default_nettype wire

// ---- nqx_s1_cordic_iter.sv ---------------------------------------
// NQX-S1 iterative CORDIC: the same arithmetic as nqx_s1_cordic.sv, one
// micro-rotation per clock on a single set of registers. Bit-exact with the
// pipelined version and with model/nqx_s1/cordic.py; accepts a new operand
// pair every NITER+1 cycles (in_ready) instead of every cycle. Used for
// area-constrained builds (Tiny Tapeout).
`default_nettype none

module nqx_s1_cordic_iter #(
    parameter integer TAG_W = 14
) (
    input  wire                        clk,
    input  wire                        rst_n,
    input  wire                        in_valid,
    output wire                        in_ready,
    input  wire                        in_vec,
    input  wire signed [`NQX_DW-1:0]   in_x,
    input  wire signed [`NQX_DW-1:0]   in_y,
    input  wire        [`NQX_ZW-1:0]   in_z,
    input  wire        [TAG_W-1:0]     in_tag,
    output reg                         out_valid,
    output reg  signed [`NQX_DW-1:0]   out_x,
    output reg  signed [`NQX_DW-1:0]   out_y,
    output reg         [`NQX_ZW-1:0]   out_z,
    output reg                         out_sat,
    output reg         [TAG_W-1:0]     out_tag,
    output wire                        busy
);
    localparam integer DW = `NQX_DW;
    localparam integer CW = `NQX_CW;
    localparam integer ZW = `NQX_ZW;
    localparam integer GB = `NQX_GB;
    localparam integer N  = `NQX_NITER;
    localparam integer KF = `NQX_KF;
    localparam integer SH = KF + GB;
    localparam integer PW = CW + KF + 1;
    localparam integer IW = $clog2(N + 1);
    localparam [IW-1:0] LAST = IW'(N - 1);
function automatic [19:0] nqx_atan(input integer i);
    case (i)
         0: nqx_atan = 20'd131072;
         1: nqx_atan = 20'd77376;
         2: nqx_atan = 20'd40884;
         3: nqx_atan = 20'd20753;
         4: nqx_atan = 20'd10417;
         5: nqx_atan = 20'd5213;
         6: nqx_atan = 20'd2607;
         7: nqx_atan = 20'd1304;
         8: nqx_atan = 20'd652;
         9: nqx_atan = 20'd326;
        10: nqx_atan = 20'd163;
        11: nqx_atan = 20'd81;
        12: nqx_atan = 20'd41;
        13: nqx_atan = 20'd20;
        14: nqx_atan = 20'd10;
        15: nqx_atan = 20'd5;
        16: nqx_atan = 20'd3;
        17: nqx_atan = 20'd1;
        default: nqx_atan = 20'd0;
    endcase
endfunction
    // Quadrant pre-rotation: identical to the pipelined version.
    wire signed [CW-1:0] ext_x = {{(CW-DW-GB){in_x[DW-1]}}, in_x, {GB{1'b0}}};
    wire signed [CW-1:0] ext_y = {{(CW-DW-GB){in_y[DW-1]}}, in_y, {GB{1'b0}}};
    wire rot_flip = in_z[ZW-1] ^ in_z[ZW-2];
    wire vec_flip = in_x[DW-1];
    wire flip     = in_vec ? vec_flip : rot_flip;
    wire [ZW-1:0] z_rot = {in_z[ZW-1] ^ rot_flip, in_z[ZW-2:0]};
    wire [ZW-1:0] z_vec = {vec_flip, {(ZW-1){1'b0}}};

    reg                 loaded;     // operands captured, iterations pending
    reg                 fin;        // iterations done, output stage next
    reg  [IW-1:0]       i;
    reg  signed [CW-1:0] x, y;
    reg         [ZW-1:0] z;
    reg                 m;
    reg  [TAG_W-1:0]    t;

    assign in_ready = !loaded && !fin;
    assign busy     = loaded || fin || out_valid;

    wire signed [CW-1:0] xsh = x >>> i;
    wire signed [CW-1:0] ysh = y >>> i;
    wire                 d   = m ? y[CW-1] : ~z[ZW-1];
    wire        [ZW-1:0] a   = nqx_atan({{(32-IW){1'b0}}, i});

    // Gain compensation and saturation: identical to the pipelined version.
    wire signed [KF:0]   kinv = `NQX_KINV;
    wire signed [PW-1:0] rnd  = 1 <<< (SH-1);
    /* verilator lint_off UNUSEDSIGNAL */
    wire signed [PW-1:0]    px = x * kinv + rnd;
    wire signed [PW-1:0]    py = y * kinv + rnd;
    /* verilator lint_on UNUSEDSIGNAL */
    wire signed [PW-SH-1:0] cx = px[PW-1:SH];
    wire signed [PW-SH-1:0] cy = py[PW-1:SH];
    localparam signed [PW-SH-1:0] HI = (1 <<< (DW-1)) - 1;
    localparam signed [PW-SH-1:0] LO = -(1 <<< (DW-1));
    wire sx_hi = cx > HI;
    wire sx_lo = cx < LO;
    wire sy_hi = cy > HI;
    wire sy_lo = cy < LO;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            loaded    <= 1'b0;
            fin       <= 1'b0;
            i         <= {IW{1'b0}};
            x         <= {CW{1'b0}};
            y         <= {CW{1'b0}};
            z         <= {ZW{1'b0}};
            m         <= 1'b0;
            t         <= {TAG_W{1'b0}};
            out_valid <= 1'b0;
            out_x     <= {DW{1'b0}};
            out_y     <= {DW{1'b0}};
            out_z     <= {ZW{1'b0}};
            out_sat   <= 1'b0;
            out_tag   <= {TAG_W{1'b0}};
        end else begin
            out_valid <= 1'b0;
            if (in_valid && in_ready) begin
                x      <= flip ? -ext_x : ext_x;
                y      <= flip ? -ext_y : ext_y;
                z      <= in_vec ? z_vec : z_rot;
                m      <= in_vec;
                t      <= in_tag;
                i      <= {IW{1'b0}};
                loaded <= 1'b1;
            end else if (loaded) begin
                x <= d ? x - ysh : x + ysh;
                y <= d ? y + xsh : y - xsh;
                z <= d ? z - a : z + a;
                i <= i + 1'b1;
                if (i == LAST) begin
                    loaded <= 1'b0;
                    fin    <= 1'b1;
                end
            end else if (fin) begin
                fin       <= 1'b0;
                out_valid <= 1'b1;
                out_x     <= sx_hi ? HI[DW-1:0] : sx_lo ? LO[DW-1:0] : cx[DW-1:0];
                out_y     <= sy_hi ? HI[DW-1:0] : sy_lo ? LO[DW-1:0] : cy[DW-1:0];
                out_z     <= z;
                out_sat   <= sx_hi | sx_lo | (~m & (sy_hi | sy_lo));
                out_tag   <= t;
            end
        end
    end
endmodule

`default_nettype wire

// ---- nqx_s1_rcode.sv ---------------------------------------------
// NQX-S1 radius code: q = #{m in 1..7 : 14*d > (2m-1)*rng}, d = r - rmin,
// i.e. round(7*d/rng) with ties rounded down. Bit-exact with
// model/nqx_s1/quant.py:radius_code.
`default_nettype none

module nqx_s1_rcode (
    input  wire signed [`NQX_DW:0]   d,
    input  wire        [`NQX_DW-1:0] rng,
    output wire        [2:0]         q
);
    localparam integer W = `NQX_DW + 5;

    wire signed [W-1:0] dx  = {{4{d[`NQX_DW]}}, d};
    wire signed [W-1:0] d14 = (dx <<< 4) - (dx <<< 1);
    wire signed [W-1:0] r1  = $signed({5'b0, rng});
    wire signed [W-1:0] r2  = r1 <<< 1;
    wire signed [W-1:0] r4  = r1 <<< 2;
    wire signed [W-1:0] r8  = r1 <<< 3;
    wire signed [W-1:0] r16 = r1 <<< 4;

    wire signed [W-1:0] t1  = r1;
    wire signed [W-1:0] t3  = r2 + r1;
    wire signed [W-1:0] t5  = r4 + r1;
    wire signed [W-1:0] t7  = r8 - r1;
    wire signed [W-1:0] t9  = r8 + r1;
    wire signed [W-1:0] t11 = r8 + t3;
    wire signed [W-1:0] t13 = r16 - t3;

    wire [6:0] gt = {d14 > t13, d14 > t11, d14 > t9, d14 > t7, d14 > t5, d14 > t3, d14 > t1};

    assign q = {2'b0, gt[0]} + {2'b0, gt[1]} + {2'b0, gt[2]} + {2'b0, gt[3]}
             + {2'b0, gt[4]} + {2'b0, gt[5]} + {2'b0, gt[6]};
endmodule

`default_nettype wire

// ---- nqx_s1_rsign.sv ---------------------------------------------
// NQX-S1 radius residual sign: s = (7*d >= q*rng), the "QJL" bit of the
// radius. Bit-exact with model/nqx_s1/quant.py:radius_code.
`default_nettype none

module nqx_s1_rsign (
    input  wire signed [`NQX_DW:0]   d,
    input  wire        [`NQX_DW-1:0] rng,
    input  wire        [2:0]         q,
    output wire                      s
);
    localparam integer W = `NQX_DW + 4;

    wire signed [W-1:0] dx = {{3{d[`NQX_DW]}}, d};
    wire signed [W-1:0] d7 = (dx <<< 3) - dx;
    wire signed [W-1:0] r1 = $signed({4'b0, rng});
    wire signed [W-1:0] qr = (q[0] ? r1 : {W{1'b0}}) + (q[1] ? (r1 <<< 1) : {W{1'b0}})
                           + (q[2] ? (r1 <<< 2) : {W{1'b0}});
    assign s = d7 >= qr;
endmodule

`default_nettype wire

// ---- nqx_s1_tcode.sv ---------------------------------------------
// NQX-S1 angle code: circular 8-sector quantizer of a ZW-bit binary angle
// plus residual sign. Bit-exact with model/nqx_s1/quant.py:angle_code.
`default_nettype none

module nqx_s1_tcode (
    input  wire [`NQX_ZW-1:0] t,
    output wire [2:0]         q,
    output wire               s
);
    localparam integer ZW = `NQX_ZW;

    wire [2:0]    tq = t[ZW-1:ZW-3] + {2'b0, t[ZW-4]};
    wire [ZW-1:0] e  = t - {tq, {(ZW-3){1'b0}}};

    assign q = tq;
    assign s = ~e[ZW-1];
endmodule

`default_nettype wire

// ---- nqx_s1_qdec.sv ----------------------------------------------
// NQX-S1 dequantizer: packed byte -> (r_hat, theta_hat).
// Bit-exact with model/nqx_s1/quant.py:decode_pair.
`default_nettype none

module nqx_s1_qdec (
    input  wire        [7:0]                         pk,
    input  wire        [`NQX_DW-1:0]                 rmin,
    input  wire        [`NQX_DW+`NQX_STEPF-5:0]      step,
    input  wire                                      refine,
    output wire signed [`NQX_DW-1:0]                 r,
    output wire        [`NQX_ZW-1:0]                 t,
    output wire                                      sat
);
    localparam integer DW = `NQX_DW;
    localparam integer ZW = `NQX_ZW;
    localparam integer F  = `NQX_STEPF;
    localparam integer SW = DW + F - 4;
    localparam integer PW = SW + 6;

    wire [2:0] qr = pk[2:0];
    wire       sr = pk[3];
    wire [2:0] qt = pk[6:4];
    wire       st = pk[7];

    wire signed [5:0] adj = refine ? (sr ? 6'sd1 : -6'sd1) : 6'sd0;
    wire signed [5:0] num = $signed({1'b0, qr, 2'b00}) + adj;

    wire signed [PW-1:0] rnd  = 1 <<< (F - 1);
    wire signed [PW-1:0] prod = num * $signed({1'b0, step}) + rnd;
    /* verilator lint_off UNUSEDSIGNAL */
    wire signed [PW-1:0] prod_q = prod;
    /* verilator lint_on UNUSEDSIGNAL */
    wire signed [PW-F-1:0] term = prod_q[PW-1:F];
    wire signed [PW-F:0]   rsum = $signed({2'b0, rmin}) + $signed({term[PW-F-1], term});

    localparam signed [PW-F:0] RMAX = (1 <<< (DW-1)) - 1;
    assign sat = rsum > RMAX;
    assign r   = sat ? RMAX[DW-1:0] : rsum[DW-1:0];

    localparam [ZW-1:0] QUARTER = 1 << (ZW - 5);

    wire [ZW-1:0] tbase = {qt, {(ZW-3){1'b0}}};
    assign t = !refine ? tbase : st ? tbase + QUARTER : tbase - QUARTER;
endmodule

`default_nettype wire

// ---- nqx_s1_div28.sv ---------------------------------------------
// NQX-S1 serial divider: step = floor(rng * 2^STEPF / 28), one quotient bit
// per cycle, DW+STEPF cycles. Bit-exact with model/nqx_s1/quant.py:radius_step.
`default_nettype none

module nqx_s1_div28 (
    input  wire                           clk,
    input  wire                           rst_n,
    input  wire                           start,
    input  wire [`NQX_DW-1:0]             rng,
    output reg  [`NQX_DW+`NQX_STEPF-5:0]  step,
    output reg                            busy
);
    localparam integer DW    = `NQX_DW;
    localparam integer F     = `NQX_STEPF;
    localparam integer NW    = DW + F;
    localparam integer CNT_W = $clog2(NW + 1);
    localparam [CNT_W-1:0] NBITS = CNT_W'(NW);

    reg [NW-1:0]    num;
    /* verilator lint_off UNUSEDSIGNAL */
    reg [NW-1:0]    quo;       // top 4 bits are always zero: rng < 2^(DW-1)
    /* verilator lint_on UNUSEDSIGNAL */
    reg [4:0]       rem;
    reg [CNT_W-1:0] cnt;

    wire [5:0] rs   = {rem, num[NW-1]};
    wire       ge   = rs >= 6'd28;
    wire [4:0] rsub = rs[4:0] - 5'd28;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            busy <= 1'b0;
            num  <= {NW{1'b0}};
            quo  <= {NW{1'b0}};
            rem  <= 5'd0;
            cnt  <= {CNT_W{1'b0}};
            step <= {(NW-4){1'b0}};
        end else if (start) begin
            busy <= 1'b1;
            num  <= {rng, {F{1'b0}}};
            quo  <= {NW{1'b0}};
            rem  <= 5'd0;
            cnt  <= NBITS;
        end else if (busy) begin
            num <= num << 1;
            quo <= {quo[NW-2:0], ge};
            rem <= ge ? rsub : rs[4:0];
            cnt <= cnt - 1'b1;
            if (cnt == 1) begin
                busy <= 1'b0;
                step <= {quo[NW-6:0], ge};
            end
        end
    end
endmodule

`default_nettype wire

// ---- nqx_s1_rf.sv ------------------------------------------------
// NQX-S1 vector register: DIM x DW flip-flops (cleared by reset), two
// asynchronous read ports and two write ports. Givens pairs within one layer
// are disjoint, so the two write ports never target the same element in
// normal operation; port B wins if they do.
`default_nettype none

module nqx_s1_rf (
    input  wire                        clk,
    input  wire                        rst_n,
    input  wire [`NQX_LOG2_DIM-1:0]    ra,
    input  wire [`NQX_LOG2_DIM-1:0]    rb,
    output wire signed [`NQX_DW-1:0]   rda,
    output wire signed [`NQX_DW-1:0]   rdb,
    input  wire                        wea,
    input  wire [`NQX_LOG2_DIM-1:0]    wa,
    input  wire signed [`NQX_DW-1:0]   wda,
    input  wire                        web,
    input  wire [`NQX_LOG2_DIM-1:0]    wb,
    input  wire signed [`NQX_DW-1:0]   wdb
);
    localparam integer DIM = `NQX_DIM;
    localparam integer DW  = `NQX_DW;

    wire [DW*DIM-1:0] flat;

    genvar e;
    generate
        for (e = 0; e < DIM; e = e + 1) begin : g_el
            reg [DW-1:0] q;
            always @(posedge clk or negedge rst_n) begin
                if (!rst_n)
                    q <= {DW{1'b0}};
                else if (web && wb == e)
                    q <= wdb;
                else if (wea && wa == e)
                    q <= wda;
            end
            assign flat[e*DW +: DW] = q;
        end
    endgenerate

    assign rda = flat[ra*DW +: DW];
    assign rdb = flat[rb*DW +: DW];
endmodule

`default_nettype wire
