#!/usr/bin/env python3
"""Export an NQX-S1 build as a Tiny Tapeout project directory.

    python tools/export_tinytapeout.py [--dim 32] [--out tinytapeout]

Produces a directory that drops into a repository created from Tiny
Tapeout's template (ttgf-verilog-template / ttihp-verilog-template):
info.yaml, src/ (wrapper + one flattened RTL file with the generated
parameters inlined), docs/info.md and a cocotb test that checks the design
bit-exactly against the model at the chosen DIM.

Pin map (24 TT I/Os):
    ui_in[7:0]   in_bus        uo_out[7:0]  out_bus
    uio[0] in    in_req        uio[1] out   in_ack
    uio[2] out   out_req       uio[3] in    out_ack
    uio[4] out   busy          uio[7:5]     unused (inputs)
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "model"))

from gen_params import atan_vh, params_vh  # noqa: E402

from nqx_s1.params import S1Params  # noqa: E402

TOP = "tt_um_hermandoronin_nqx_s1"
RTL_ORDER = [
    "nqx_s1_top.sv", "nqx_s1_hsio.sv", "nqx_s1_core.sv", "nqx_s1_cordic.sv",
    "nqx_s1_cordic_iter.sv", "nqx_s1_rcode.sv", "nqx_s1_rsign.sv", "nqx_s1_tcode.sv",
    "nqx_s1_qdec.sv", "nqx_s1_div28.sv", "nqx_s1_rf.sv",
]


def flatten_rtl(p: S1Params) -> str:
    params = params_vh(p).replace("// GENERATED", "// Inlined, GENERATED")
    atan = "\n".join(atan_vh(p).splitlines()[2:])
    out = [
        f"// NQX-S1, DIM={p.dim}: flattened by tools/export_tinytapeout.py from nqx-silicon/rtl.",
        "// Do not edit; regenerate instead.",
        "/* verilator lint_off DECLFILENAME */",
        params,
    ]
    for name in RTL_ORDER:
        text = (ROOT / "rtl" / name).read_text()
        text = text.replace('`include "nqx_s1_params.vh"\n', "")
        text = re.sub(r'^\s*`include "nqx_s1_atan.vh"\s*$', atan, text, flags=re.M)
        out.append(f"// ---- {name} " + "-" * max(0, 60 - len(name)) + "\n" + text)
    return "\n".join(out)


WRAPPER = """/*
 * NQX-S1 (NautilusQuant golden-angle KV compression engine) for Tiny Tapeout.
 * SPDX-License-Identifier: Apache-2.0
 */
`default_nettype none

module {top} (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
    wire in_ack, out_req, busy;

    assign uio_oe  = 8'b0001_0110;
    assign uio_out = {{3'b000, busy, 1'b0, out_req, in_ack, 1'b0}};

    nqx_s1_top #(.ITER_CORDIC(1)) u_nqx (
        .clk     (clk),
        .rst_n   (rst_n),
        .in_bus  (ui_in),
        .in_req  (uio_in[0]),
        .in_ack  (in_ack),
        .out_bus (uo_out),
        .out_req (out_req),
        .out_ack (uio_in[3]),
        .busy    (busy)
    );

    wire _unused = &{{ena, uio_in[7:4], uio_in[2:1], 1'b0}};
endmodule

`default_nettype wire
"""

INFO = """# Tiny Tapeout project information (generated by nqx-silicon/tools/export_tinytapeout.py)
project:
  title:        "NQX-S1 golden-angle KV-cache compressor"
  author:       "Herman Doronin"
  discord:      ""
  description:  "NautilusQuant: golden-angle Givens rotation (phase accumulator + CORDIC), polar 3+1-bit quantization of {dim}-element int16 vectors"
  language:     "SystemVerilog"
  clock_hz:     25000000

  tiles: "{tiles}"

  top_module:  "{top}"

  source_files:
    - "{top}.v"
    - "nqx_s1_dim{dim}.v"

pinout:
  # Inputs
  ui[0]: "in_bus[0]"
  ui[1]: "in_bus[1]"
  ui[2]: "in_bus[2]"
  ui[3]: "in_bus[3]"
  ui[4]: "in_bus[4]"
  ui[5]: "in_bus[5]"
  ui[6]: "in_bus[6]"
  ui[7]: "in_bus[7]"

  # Outputs
  uo[0]: "out_bus[0]"
  uo[1]: "out_bus[1]"
  uo[2]: "out_bus[2]"
  uo[3]: "out_bus[3]"
  uo[4]: "out_bus[4]"
  uo[5]: "out_bus[5]"
  uo[6]: "out_bus[6]"
  uo[7]: "out_bus[7]"

  # Bidirectional pins
  uio[0]: "in_req (in)"
  uio[1]: "in_ack (out)"
  uio[2]: "out_req (out)"
  uio[3]: "out_ack (in)"
  uio[4]: "busy (out)"
  uio[5]: ""
  uio[6]: ""
  uio[7]: ""

# Do not change!
yaml_version: 6
"""

DOCS = """## How it works

NQX-S1 compresses a {dim}-element vector of signed 16-bit integers (an LLM
KV-cache head slice) into {pkt} bytes and restores it. The pipeline is
NautilusQuant: Givens rotations whose angles follow the golden angle,
generated by a 32-bit phase accumulator (increments 0x61C88647 and
0x9E3779B9) and applied by a CORDIC with shifts and adds only. Then comes a
polar transform, a 3-bit radius and 3-bit circular angle code per pair, and
one residual bit per value. The design is bit-exact with the Python model in
nqx-silicon/model and uses the area-saving iterative CORDIC.

Full specification: https://github.com/hermandoronin/NautilusQuant/tree/main/nqx-silicon/spec

## How to test

The host writes command bytes on ui_in with a 4-phase handshake
(uio[0] in_req / uio[1] in_ack) and reads results on uo_out
(uio[2] out_req / uio[3] out_ack):

1. Set ui_in, raise in_req, wait for in_ack, drop in_req, wait for in_ack low.
2. When out_req is high, read uo_out, raise out_ack, wait for out_req low,
   drop out_ack.

Send `72 00` (read CSR 0): the chip answers `31 58 51 4E` ("NQX1").
Send `60` followed by {inb} bytes (a vector) to receive a {pkt}-byte packet.
Send `61` followed by the packet to get the vector back.

## External hardware

None. The demo board's microcontroller drives the handshake.
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dim", type=int, default=32)
    ap.add_argument("--tiles", default="4x4")
    ap.add_argument("--out", type=Path, default=ROOT / "tinytapeout")
    args = ap.parse_args()
    p = S1Params(dim=args.dim)

    out = args.out
    if out.exists():
        shutil.rmtree(out)
    (out / "src").mkdir(parents=True)
    (out / "docs").mkdir()
    (out / "test").mkdir()

    (out / "src" / f"nqx_s1_dim{p.dim}.v").write_text(flatten_rtl(p))
    (out / "src" / f"{TOP}.v").write_text(WRAPPER.format(top=TOP))
    (out / "info.yaml").write_text(INFO.format(dim=p.dim, tiles=args.tiles, top=TOP))
    (out / "docs" / "info.md").write_text(
        DOCS.format(dim=p.dim, pkt=p.packet_bytes, inb=2 * p.dim)
    )
    shutil.copytree(ROOT / "model" / "nqx_s1", out / "test" / "nqx_s1",
                    ignore=shutil.ignore_patterns("__pycache__"))
    shutil.copy(ROOT / "tools" / "tt_test" / "README.md", out / "README.md")
    shutil.copy(ROOT / "tools" / "tt_test" / "gitignore", out / ".gitignore")
    shutil.copy(ROOT / "tools" / "tt_test" / "config.json", out / "src" / "config.json")
    shutil.copy(ROOT / "tools" / "tt_test" / "requirements.txt", out / "test" / "requirements.txt")
    for f in ("tb.v", "test.py", "Makefile"):
        text = (ROOT / "tools" / "tt_test" / f).read_text()
        text = text.replace("@TOP@", TOP).replace("@DIM@", str(p.dim))
        (out / "test" / f).write_text(text)
    print(f"exported Tiny Tapeout project to {out} (DIM={p.dim}, tiles={args.tiles})")


if __name__ == "__main__":
    main()
