#!/usr/bin/env python3
"""Generate rtl/nqx_s1_params.vh and rtl/nqx_s1_atan.vh from model/nqx_s1/params.py.

Usage:
    python tools/gen_params.py [--dim 128] [--out-dir rtl]
    python tools/gen_params.py --check      # fail if the checked-in files are stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "model"))

from nqx_s1.params import CHIP_ID, INC_DEFAULT, VERSION, S1Params  # noqa: E402

HEADER = "// GENERATED by tools/gen_params.py from model/nqx_s1/params.py -- do not edit.\n"


def params_vh(p: S1Params) -> str:
    rows = [
        ("NQX_DIM", p.dim),
        ("NQX_LOG2_DIM", p.log2_dim),
        ("NQX_IN_W", p.in_w),
        ("NQX_FW", p.fw),
        ("NQX_DW", p.dw),
        ("NQX_GB", p.gb),
        ("NQX_CW", p.cw),
        ("NQX_ZW", p.zw),
        ("NQX_NITER", p.n_iter),
        ("NQX_KF", p.kf),
        ("NQX_KINV", p.kinv),
        ("NQX_STEPF", p.step_f),
        ("NQX_HB", p.hb),
        ("NQX_NPAIRS", p.n_pairs),
        ("NQX_L3_STRIDE", p.l3_stride),
        ("NQX_PKT_BYTES", p.packet_bytes),
        ("NQX_CORDIC_LAT", p.cordic_latency),
    ]
    out = [HEADER, "`ifndef NQX_S1_PARAMS_VH\n`define NQX_S1_PARAMS_VH\n\n"]
    for name, val in rows:
        out.append(f"`define {name:<16} {val}\n")
    out.append("\n")
    for i, inc in enumerate(INC_DEFAULT):
        out.append(f"`define NQX_INC{i}_RESET  32'h{inc:08X}\n")
    out.append(f"`define NQX_CHIP_ID      32'h{CHIP_ID:08X}\n")
    out.append(f"`define NQX_VERSION      32'h{VERSION:08X}\n")
    out.append(f"`define NQX_PARAMS_WORD  32'h{p.params_word():08X}\n")
    out.append("\n`endif\n")
    return "".join(out)


def atan_vh(p: S1Params) -> str:
    out = [HEADER, "// atan(2^-i) as a ZW-bit binary angle (full turn = 2^ZW).\n"]
    out.append(f"function automatic [{p.zw - 1}:0] nqx_atan(input integer i);\n")
    out.append("    case (i)\n")
    for i, a in enumerate(p.atan_table):
        out.append(f"        {i:>2}: nqx_atan = {p.zw}'d{a};\n")
    out.append(f"        default: nqx_atan = {p.zw}'d0;\n")
    out.append("    endcase\nendfunction\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dim", type=int, default=128)
    ap.add_argument("--out-dir", type=Path, default=ROOT / "rtl")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    p = S1Params(dim=args.dim)
    files = {
        args.out_dir / "nqx_s1_params.vh": params_vh(p),
        args.out_dir / "nqx_s1_atan.vh": atan_vh(p),
    }
    stale = []
    for path, text in files.items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(path)
        else:
            path.write_text(text)
            print(f"wrote {path}")
    if stale:
        for path in stale:
            print(f"stale: {path} (run tools/gen_params.py)", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
