// GENERATED by tools/gen_params.py from model/nqx_s1/params.py -- do not edit.
`ifndef NQX_S1_PARAMS_VH
`define NQX_S1_PARAMS_VH

`define NQX_DIM          128
`define NQX_LOG2_DIM     7
`define NQX_IN_W         16
`define NQX_FW           4
`define NQX_DW           24
`define NQX_GB           2
`define NQX_CW           28
`define NQX_ZW           20
`define NQX_NITER        18
`define NQX_KF           18
`define NQX_KINV         159188
`define NQX_STEPF        8
`define NQX_HB           3
`define NQX_NPAIRS       64
`define NQX_L3_STRIDE    32
`define NQX_PKT_BYTES    70
`define NQX_CORDIC_LAT   20

`define NQX_INC0_RESET  32'h61C88647
`define NQX_INC1_RESET  32'h9E3779B9
`define NQX_INC2_RESET  32'h00000000
`define NQX_CHIP_ID      32'h4E515831
`define NQX_VERSION      32'h00010000
`define NQX_PARAMS_WORD  32'h14121807

`endif
